[platformio]
default_envs = airdos04
boards_dir = ../boards
src_dir = src

[env]
platform = atmelavr
framework = arduino
board = batdatunit01c
platform_packages =
  framework-arduino-avr-mightycore @ 3.0.2
board_build.variant = standard
board_build.f_cpu = 8000000L
lib_deps =
  robtillaart/SHT31@0.5.0
  robtillaart/MS5611@0.4.0
monitor_speed = 115200
upload_protocol = arduino
upload_speed = 57600
build_flags =
  -DCHANNELS=0

# Don't compile old Arduino build artifacts
build_src_filter =
  +<*>
  -<build/>

[env:airdos04]

[env:bootloader_stk500v2]
upload_protocol = stk500v2
extra_scripts =
  post:../scripts/upload_bootloader.py
